time snakemake kallisto/gex/c1
time snakemake kallisto/features/H1_S6.HTO_A_13
time snakemake kallisto/features/A1_S5.ADT_15
time snakemake cite-seq-count/A1_S5_d1_ADT
time snakemake cite-seq-count/H1_S6_d1_HTO
time snakemake cellranger_A1
time snakemake cellranger_H1
time snakemake cite-seq-count/H1_S6_d1_HTO_nocorrect
time snakemake cite-seq-count/A1_S5_d1_ADT_nocorrect
